/*
 * ViewFrame.java
 */

public class ViewFrame  extends javax.swing.JFrame implements View, ViewObserver {
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField input;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField output;
  // End of variables declaration//GEN-END:variables
  
  private Model m1;
  private Model m2;
  private Controller controller;
  
  /** Creates new form ViewFrame */
  public ViewFrame(Model m1, Model m2, Controller controller) {
    initComponents();
    this.m1 = m1;
    this.m2 = m2;
    m1.registerView(this);
    m2.registerView(this);
    this.controller = controller;
    
  }
  
  /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    
    jLabel1 = new javax.swing.JLabel();
    input = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    output = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    
    jLabel1.setText("Input");
    
    jLabel2.setText("Output");
    
    output.setEnabled(false);
    
    jButton1.setText("Pig Latin");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    
    jButton2.setText("Flame");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jLabel2))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(output)
                                                                                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jButton1)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                                                    .addComponent(jButton2)))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                             );
    layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(jLabel1)
                                                      .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(jLabel2)
                                                      .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(jButton1)
                                                      .addComponent(jButton2))
                                          .addContainerGap(27, Short.MAX_VALUE))
                           );
    
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  // This is called if the Pig Latin button is pressed
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    controller.processModel(m1, input.getText());
  }//GEN-LAST:event_jButton1ActionPerformed
  
  // This is called if the Flame button is pressed
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    controller.processModel(m2, input.getText());
  }//GEN-LAST:event_jButton2ActionPerformed
  
  
  public void display(String s) {
    output.setText(s);
  }
  
  
  
  public void createView() {
    setVisible(true);
  }
  
  public void updateView(String message) {
    
    /** This needs to be filled in **/
    output.setText(message);
    
  }
}
